
class PracticeFormPage:
    FIRST_NAME = "//input[@id='firstName']"
    LAST_NAME = "//input[@id='lastName']"
    EMAIL = "//input[@id='userEmail']"
    GENDER_MALE = "//label[@for='gender-radio-1']"
    GENDER_FEMALE = "//label[@for='gender-radio-2']"
    MOBILE = "//input[@id='userNumber']"
    DATE_OF_BIRTH = "//input[@id='dateOfBirthInput']"
    SUBJECTS = "//input[@id='subjectsInput']"
    HOBBY_SPORTS = "//label[@for='hobbies-checkbox-1']"
    HOBBY_READING = "//label[@for='hobbies-checkbox-2']"
    HOBBY_MUSIC = "//label[@for='hobbies-checkbox-3']"
    PICTURE = "//input[@id='uploadPicture']"
    ADDRESS = "//textarea[@id='currentAddress']"
    STATE = "//div[@id='state']"
    CITY = "//div[@id='city']"
    SUBMIT = "//button[@id='submit']"
    MODAL_HEADER = "//div[@class='modal-header']"
    MODAL_BODY = "//div[@class='modal-body']"
    CLOSE_BUTTON = "//button[@id='closeLargeModal']"